### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by jikuja**
* startup script creation changes
  * use relative path for downloaded adoptium JRE
  * added quotes around java command for extra safety
* Fixed --path with adoptium downloader
* added sed flags in build file for OS X compatibility 
* added todo for unhandled --path usage

### CODE REVIEW

**Comment by jikuja** [comment]
Tested only on OS X. Testing with Windows later unless someone else is faster.

**Comment by jikuja** [comment]
Tested on windows: works and current bugs are gone.

Also removed unneeded TODO for --path.

**Comment by Gaz492** [comment]
This has been merged in internally as this repo syncs from a private git and can be closed

**Comment by jikuja** [comment]
Merged

**Pull request closed without merging**
